# Generated by Django 6.0 on 2025-12-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subjects', models.JSONField(default=list, help_text='List of high school subjects')),
                ('grades', models.JSONField(default=dict, help_text='Dictionary of subject:grade pairs')),
                ('favorite_subjects', models.JSONField(default=list, help_text='Subjects the user enjoyed most')),
                ('hobbies', models.JSONField(default=list, help_text='List of hobbies and extracurricular activities')),
                ('interests', models.JSONField(default=list, help_text='Topics and areas of interest')),
                ('personality_type', models.CharField(blank=True, help_text='MBTI personality type (e.g., INTJ, ENFP)', max_length=4)),
                ('personality_scores', models.JSONField(default=dict, help_text='Detailed personality test scores')),
                ('recommendations', models.JSONField(default=list, help_text='Generated course recommendations')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
